package:
  name: nifti_clib
  version: {{ GIT_DESCRIBE_TAG }}

source:
    -    rev: {{ GIT_DESCRIBE_TAG }}
    -    git_url: ../

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - cmake
  host:
    - zlib
    - expat

test:
  commands:
    - test -f ${PREFIX}/include/nifti1.h
    - test -f ${PREFIX}/lib/libniftiio.a

about:
  home: https://github.com/NIFTI-Imaging/nifti_clib
  license: Public Domain
  license_family: PUBLIC-DOMAIN
  license_file: LICENSE
  summary: 'C library for IO with the nifti file format.'

extra:
  recipe-maintainers:
    - leej3
